### DISCUSSION TITLE
Ubuntu 22.04 LTS仅使用Netplan单配置文件配置内核Wireguard+Cloudflare WARP

### DISCUSSION THREAD

**Discussion by lxsq** [XTLS/Xray-core#2240] [Show and tell]
**安装DKMS版的wireguard：**
`sudo apt install wireguard-dkms`
或者按照[官网指南](https://www.wireguard.com/install/)
Wireguard于2020年3月正式合并进了Linux 5.6内核，以上版本可以忽略此步。

**使用[wgcf](https://github.com/ViRb3/wgcf)或者[warp-reg](https://github.com/badafans/warp-reg)注册**

**新建配置文件/etc/netplan/warp.yaml:**
```
network:
  version: 2
  tunnels:
    wgcf:
      mode: wireguard
      addresses: [172.16.0.2/32, "2***/128"]
      key: ***
      mtu: 1280
      peers:
        - endpoint: engage.cloudflareclient.com:2408
          allowed-ips: [0.0.0.0/0, "::/0"]
          keys:
            public: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=
          keepalive: 30
      routes:
        - to: 0.0.0.0/0
          scope: link
          table: 205
        - to: "::/0"
          on-link: true
          table: 205
      routing-policy:
        - from: 172.16.0.2/32
          table: 205
        - from: "2***/128"
          table: 205
#下面的规则不用fwmark功能可以省略
        - from: 0.0.0.0/0
          mark: 53199
          table: 252
        - from: ::/0
          mark: 53199
          table: 252
```

**完成后执行`sudo netplan try`应用配置。**

**运行`ip addr`查看网卡**
```
N: wgcf: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1280 qdisc noqueue state UNKNOWN group default qlen 1000
    link/none
    inet 172.16.0.2/32 scope global wgcf
       valid_lft forever preferred_lft forever
    inet6 2***/128 scope global
       valid_lft forever preferred_lft forever
```

**使用[sendThrough](https://xtls.github.io/config/outbound.html#outboundobject)可以实现IPv4/IPv6分流**
缺点：需要单独配置IPv4与IPv6
```
{
        "protocol":"freedom",
        "sendThrough": "26***",
        "settings":{
                "domainStrategy":"UseIPv6"
        },
        "tag":"warp-IPv6-out"
},
{
        "protocol":"freedom",
        "sendThrough": "172.16.0.2",
        "settings":{
                "domainStrategy":"UseIPv4"
        },
        "tag":"warp-IPv4-out"
}
```

**使用[Sockopt](https://xtls.github.io/config/transport.html#sockoptobject)的网卡分流。**
缺点：无法使用UDP https://github.com/XTLS/Xray-core/issues/1930
`"interface": "wgcf"`

**也可以使用[Sockopt](https://xtls.github.io/config/transport.html#sockoptobject)的mark功能**
缺点：需要更高的权限
`"mark": 53199`
