### DISCUSSION TITLE
MCI DPI got super aggressive!

### DISCUSSION THREAD

**Discussion by amir-devman** [XTLS/Xray-core#2741] [General]
For the last 10 days until now, we in Iran have been experiencing a massive DPI detection on MCI (not any other ISPs, rest are fine) for xray-core based protocol mostly reality.
It looks like it doesn't matter what IP or SNI you're using or how many are using a proxy server, your IP gets blocked within a few hours no matter how much traffic you have, you just get blocked...(at least this is my experience and people around me)

And you only can send data which means The Xray-cores accepts the connection but cannot send back the response while the IP is blocked, I don't know what the solution is and at this point xray-core or any other protocol is useless... and the only solution is to find a non-block IP address every hour after your server got blocked and again you get blocked... this is the loop we are facing and it is getting more aggressive and more accurate over time. (I think it can be because of people used any IP addresses and made them graylisted)

I think we should step forward towards this situation and find a way to mitigate this because protocols like Reality doing nothing currently.
Is there anything we should do in our configuration or changing the keys/shortIds or what because they seemed to be not working?

**Comment by ashad765** [comment]
I'm using Reality right now with my own domain (steal oneself) on MCI and it just working fine. Stealing SNI will be easily detected by just a simple DNS resolve because your SNI won't resolve to your vps IP.

**Reply by amir-devman** [reply]
I did not steal SNI, I used my own

**Comment by shakibamoshiri** [comment]
This is not about xray or any other VPN servers, MCI is targeting all the suspicious servers and throttle/disallow TLS handshake for those IPs, So any TLS handshake will fail . You can see this using WireShark .

TLS handshake has 6 steps, with MCI it never completes and you will see TCP re-transmission till the clients stops     
By the way this major shift from MCI is not applied nationwide , mostly 
- Tehran
- Kurdistan
- Systan and Baluchstan

has been affected

**Reply by amir-devman** [reply]
It's not only TLS.
And I'm not living in either of those states but it's happening.

**Reply by ashad765** [reply]
I'm not living in this three places, that could explain why I can connect to my server without any problem.
If only TLS handshakes are throttling on MCI then you should be able to connect first with other ISP (like MTN) and then switch your internet to MCI. Can you confirm this?

**Reply by amir-devman** [reply]
That was possible last week with Wireguard but now, it's not connecting, I cannot receive any data with any protocol such as reality or wireguard.

**Reply by shakibamoshiri** [reply]
@amir-devman 
using Xray or v2ray clinets -- these do not have that much log  
You can use other VPN clients and protocols to see all fail
- TLS handshake failed 
- SSL negotiation timeout 

And checking with WireGuard tells exactly that 4 steps complete but never the rest  
Plus seeing HAproxy log, lots of TLS handshake failure ...

**Reply by shakibamoshiri** [reply]
@ashad765 
Yes. I have tested this and 100% sure that MCI restriction differs from city to city  
Even I noticed in a city one MCI sim-card could not connect while and an older one had no issue.  
To me definitely they are testing / experimenting something   

Please guide/give me a proper configuration to test

**Reply by ashad765** [reply]
Hy2 can do TLS handshakes with 2 steps. Can you test and see if it can connect?

**Reply by shakibamoshiri** [reply]
@ashad765 
I am new to xray , so please give me some docs to get started or I will find more about Hy2  
Mostly I tested xary - ws - tls (with and without CDN).    
I assume if Hy2 uses UDP your hypothesis should work

**Reply by ashad765** [reply]
[Hysteria](https://github.com/apernet/hysteria)
[Hysteria 2](https://v2.hysteria.network/)

**Reply by shakibamoshiri** [reply]
@ashad765 
Testing it with three clients
- linux main app
- windows v2rayN https://github.com/2dust/v2rayN/releases
- android https://github.com/MatsuriDayo/NekoBoxForAndroid/releases/download/1.2.9/NB4A-1.2.9-arm64-v8a.apk

None worked. On Android for a foreign server error was "timeout" and for a domestic server error was "unknown ssl certificate".  

For cert LetsCrypt being used.  

I assume either the server or client configuration is wrong.  
If you have a proper working configuration please share it while 
- server address
- password
- etc
have been removed , I add my own 

here is the server I used

```yaml
listen: :443
tls:
  cert: /etc/example.com/cert.pem
  key: /etc/example.com/privkey.pem
obfs:
  type: salamander
  salamander:
    password: **********
auth:
  type: password
  password: *****************
quic:
  initStreamReceiveWindow: 8388608
  maxStreamReceiveWindow: 8388608
  initConnReceiveWindow: 20971520
  maxConnReceiveWindow: 20971520
  maxIdleTimeout: 60s
  maxIncomingStreams: 1024
  disablePathMTUDiscovery: false
bandwidth:
  up: 1 gbps
  down: 1 gbps
ignoreClientBandwidth: false
disableUDP: false
udpIdleTimeout: 60s
resolver:
  type: udp
  tcp:
    addr: 8.8.8.8:53
    timeout: 4s
  udp:
    addr: 8.8.4.4:53
    timeout: 4s
  tls:
    addr: 1.1.1.1:853
    timeout: 10s
    sni: cloudflare-dns.com
    insecure: false
  https:
    addr: 1.1.1.1:443
    timeout: 10s
    sni: cloudflare-dns.com

```

and client 

```yaml
server: *.*.*.*:443
auth: ***************
transport:
  type: udp
  udp:
    hopInterval: 30s
obfs:
  type: salamander
  salamander:
    password: ************
tls:
  sni: *********
  insecure: false
bandwidth: 
  up: 20 mbps
  down: 100 mbps
quic:
  initStreamReceiveWindow: 8388608 
  maxStreamReceiveWindow: 8388608 
  initConnReceiveWindow: 20971520 
  maxConnReceiveWindow: 20971520 
  maxIdleTimeout: 30s 
  keepAlivePeriod: 10s 
  disablePathMTUDiscovery: false
fastOpen: true
lazy: true
socks5:
  listen: 127.0.0.1:10808
http:
  listen: 127.0.0.1:10809
```

**Reply by ashad765** [reply]
Private key should be in .key format and not .pem
(If .pem file are in Base64 format it won't make any different, but maybe your .pem file are in binary format)
Here is a very minimal config
server config

```
listen: :443
tls:
  cert: your_cert.crt
  key: your_key.key
auth:
  type: password
  password: yourpassword
masquerade: 
  type: proxy
  proxy:
    url: https://apple.com/
    rewriteHost: true
```

And client

```
server: yourdomain:443
auth: yourpassword
bandwidth:
  up: 20 mbps
  down: 100 mbps
socks5:
  listen: 127.0.0.1:1080
http:
  listen: 127.0.0.1:8080
```
