### DISCUSSION TITLE
粗略性能测试: gRPC / TUIC /  Hysteria2 / XTLS / 隧道套娃

### DISCUSSION THREAD

**Discussion by qwerr0** [XTLS/Xray-core#2925] [Performance]
假设在 XTLS Reality 隧道里跑 gRPC(关闭TLS和Reality流控), 是否存在 TLS in TLS 问题?

**Comment by qwerr0** [comment]
在个人电脑上简单测试了一下性能, 有一些新的发现
SS(AES) + gRPC(无加密)
带宽: 7.92G

SS(CHACHA20) + gRPC(无加密)
带宽: 6.54G

SS(Plain) + gRPC(无加密)
带宽: 9.31G

VLESS(无加密) + gRPC(无加密)
带宽: 9.38G

VLESS(Reality) + gRPC(无加密)
带宽: 5.18G

gRPC(无加密)
带宽: 10.4G

gRPC(Reality)
带宽: 7G

VLESS(Reality) + gRPC(Reality)
带宽: 7.37G

VLESS(Reality)
带宽: 23.9G

VLESS(无加密)
带宽: 24.4G

**Reply by qwerr0** [reply]
带宽不是20G以上时CPU占用大概在40%~60%, gRPC 跑在隧道上时, 使用 Reality 性能比不加密还强

**Reply by qwerr0** [reply]
测试使用 iperf3 -P 24 -R, gRPC 开启了 tcpMptcp, tcpNoDelay, multiMode, tcpFastOpen(日志警告说不支持)

**Reply by qwerr0** [reply]
带宽跑得越高, 内存占用就越高, 带宽不到20GB时内存占用大概都是250MB左右

**Comment by qwerr0** [comment]
为了更贴合实际情况一些使用如下配置测试(数据看个大概):
代理服务端信息:
广州移动 Platinum 8124M 2C2G
中转限速 800Mbps 单线程限速 500Mbps
Xray 最新版

代理客户端信息:
红米AX6 ARM64 4核x1.2G 实际最大内存400M  (IP转发开启且不能关闭)
Clash Meta Alpha 分支手动编译最新版 使用TProxy方式代理

测速客户端信息:
个人电脑 性能较好
使用 iperf3 -P 4 -R 对中转进行测速

测试使用的协议 约定:
VLESS 指 VLESS + TCP + 无任何加密和流控
gRPC 指 VLESS + gRPC + 无任何加密和流控
VLESS Reality 指 VLESS + TCP + Reality (VLESS-TCP-XTLS-Vision-REALITY)
gRPC Reality 指 VLESS + gRPC + Reality (VLESS-gRPC-REALITY)
Trojan 未测

(测速客户端 iperf3 <-> 代理客户端 <-> 中转) <=> (中转 iperf3)

按照如下格式列出数据:
协议名称
测速平均速率 路由器的CPU大概占用

VLESS Reality (单线程测速 -P 1)
510Mbps 40%

VLESS Reality
744Mbps 85%

VLESS
680Mbps 65%
(不清楚为什么裸奔反而跑不满 测试了两次也是这样)

gRPC Reality
340Mbps 65%
(内存占用很高 当梯子跑SpeedTest多线程测速会OOM导致掉速)

gRPC
388Mbps 70%

SS-CHA
662Mbps 85%

SS-AES
729Mbps 75%

VLESS Reality + VLESS Reality
665Mbps 80%

VLESS Reality + VLESS
696Mbps 85%

gRPC Reality + gRPC Reality
240Mbps 80%

gRPC Reality + VLESS
269Mbps 75%

gRPC Reality + VLESS Reality
246Mbps 75%

gRPC + VLESS Reality
400Mbps 85%

gRPC + VLESS
400Mbps 80%

gRPC + SS(AES)
400Mbps 85%

gRPC + SS(ChaCha)
400Mbps 85%

**Reply by qwerr0** [reply]
Clash 测试使用的关键配置:
```yaml
tunnels:
  - tcp,127.0.0.1:1000,中转地址:1000,隧道
  - tcp,127.0.0.1:1001,中转地址:1001,隧道
  - tcp,127.0.0.1:1002,中转地址:1002,隧道
  - tcp,127.0.0.1:1003,中转地址:1003,隧道
  - tcp,127.0.0.1:1004,中转地址:1004,隧道
  - tcp,127.0.0.1:1005,中转地址:1005,隧道
  - tcp,127.0.0.1:1006,中转地址:1006,隧道

proxies:
  - { name: 'vless-reality', type: vless, server: 中转地址, port: 1000, uuid: 1ed783f9-b479-47dc-86de-277b28fa2b7e, network: tcp, servername: d1.awsstatic.com, udp: true, tls: true, flow: xtls-rprx-vision, reality-opts: { public-key: 公钥, short-id: 114514 }, client-fingerprint: chrome }
  - { name: 'vless', type: vless, server: 中转地址, port: 1001, uuid: 1ed783f9-b479-47dc-86de-277b28fa2b7e, network: tcp, udp: true, tls: false }
  - { name: 'grpc-reality', type: vless, server: 中转地址, port: 1002, uuid: 1ed783f9-b479-47dc-86de-277b28fa2b7e, network: grpc, servername: d1.awsstatic.com, udp: true, tls: true, grpc-opts: { grpc-service-name: g }, reality-opts: { public-key: 公钥, short-id: 114514 }, client-fingerprint: chrome }
  - { name: 'grpc', type: vless, server: 中转地址, port: 1003, uuid: 1ed783f9-b479-47dc-86de-277b28fa2b7e, network: grpc, udp: true, tls: false, grpc-opts: { grpc-service-name: g } }
  - { name: 'ss-cha', type: ss, server: 中转地址, port: 1004, cipher: chacha20-ietf-poly1305, password: 密码, udp: true }
  - { name: 'ss-aes', type: ss, server: 中转地址, port: 1005, cipher: aes-128-gcm, password: 密码, udp: true }
  - { name: 'tun-vless-reality', type: vless, server: 127.0.0.1, port: 1000, uuid: 1ed783f9-b479-47dc-86de-277b28fa2b7e, network: tcp, servername: d1.awsstatic.com, udp: true, tls: true, flow: xtls-rprx-vision, reality-opts: { public-key: 公钥, short-id: 114514 }, client-fingerprint: chrome }
  - { name: 'tun-vless', type: vless, server: 127.0.0.1, port: 1001, uuid: 1ed783f9-b479-47dc-86de-277b28fa2b7e, network: tcp, udp: true, tls: false }
  - { name: 'tun-grpc-reality', type: vless, server: 127.0.0.1, port: 1002, uuid: 1ed783f9-b479-47dc-86de-277b28fa2b7e, network: grpc, servername: d1.awsstatic.com, udp: true, tls: true, grpc-opts: { grpc-service-name: g }, reality-opts: { public-key: 公钥, short-id: 114514 }, client-fingerprint: chrome }
  - { name: 'tun-grpc', type: vless, server: 127.0.0.1, port: 1003, uuid: 1ed783f9-b479-47dc-86de-277b28fa2b7e, network: grpc, udp: true, tls: false, grpc-opts: { grpc-service-name: g } }
  - { name: 'tun-ss-cha', type: ss, server: 127.0.0.1, port: 1004, cipher: chacha20-ietf-poly1305, password: 密码, udp: true }
  - { name: 'tun-ss-aes', type: ss, server: 127.0.0.1, port: 1005, cipher: aes-128-gcm, password: 密码, udp: true }
  - { name: 'trojan-grpc', type: trojan, server: 中转地址, port: 1006, network: grpc, udp: true, password: 密码, tls: true, sni: d1.awsstatic.com, skip-cert-verify: true, grpc-opts: { grpc-service-name: g } }
  - { name: 'tun-trojan-grpc', type: trojan, server: 127.0.0.1, port: 1006, network: grpc, udp: true, password: 密码, tls: true, sni: d1.awsstatic.com, skip-cert-verify: true, grpc-opts: { grpc-service-name: g } }

proxy-groups:
  - name: 代理
    type: select
    proxies: [vless-reality, vless, grpc-reality, grpc, ss-cha, ss-aes, trojan-grpc, tun-vless-reality, tun-vless, tun-grpc-reality, tun-grpc, tun-ss-cha, tun-ss-aes, tun-trojan-grpc]

  - name: 隧道
    type: select
    proxies: [vless-reality, vless, grpc-reality, grpc, ss-cha, ss-aes, trojan-grpc]
```
