### DISCUSSION TITLE
Linux (ubuntu) 數據進出站

### DISCUSSION THREAD

**Discussion by Naruse-developer** [XTLS/Xray-core#3664] [Q&A]
>[!note] 
問題描述
我在第三方提供商買了一個家庭網絡的OPENVPN,因OPENVPN內地已不適用,所以我在伺服器上面安裝了OPENVPN客戶端
連接完成之後會出現一個tun0的虛擬網卡.但是完成連接之後無法ping通伺服器,且部署的Xray以及nignx皆無法正常通信<br>
我想要的預期效果是 internet (xray) => eth0 (public 8.8.8.8:23333) => tun0 (private 10.0.8.10:23333) => internet (xray)
使用xray時的IPV4將會變成為tun0 openvpn伺服器的IP 即下列openvpn檔中的IP ,而非原本的伺服器的IP
請問如何實現該效果？
xray的配置上沒有問題的,如果需要的話請在下列說明,只是在listen的地址變更為10.0.8.10

>[!Caution]
使用過的方法(皆無效)

1.設置路由規則
完成後 SSH / Xray / nignx皆無法正常通信
```
sudo ip route add default dev tun0
sudo ip rule add from <eth0_ip_address> lookup 100
sudo ip route add table 100 default dev tun0
```

2.gost 本地轉發

```
services:
- name: service-0
  addr: :23333
  handler:
    type: tcp
  listener:
    type: tcp
    forwarder:
      nodes:
      - name: target-0
        addr: 10.0.8.10:23333 #和xray的listen地址/端口一致
log:
  level: info
  format: json
  output: /etc/gost/log.log
  rotation:
    maxSize: 1000
    maxAge: 30
    maxBackups: 1
    localTime: true
    compress: false
```

>[!note]
這是openvpn的配置檔
```
dev tun
proto tcp
remote 126.99.1.1 1194
cipher AES-128-CBC
auth SHA1
resolv-retry infinite
nobind
persist-key
persist-tun
client
verb 0
#auth-user-pass
route-nopull #禁止從伺服器端獲得路由

#部分配置省略
```
