### DISCUSSION TITLE
sendThrough的随机IP地址该如何配置系统？

### DISCUSSION THREAD

**Discussion by MoldyPeaches** [XTLS/Xray-core#4090] [Q&A]
文档中说到：

> 允许在其中填入 IPv6 CIDR 块(如114:514:1919:810::/64)，Xray将会使用地址块中随机的IP地址对外发起连接。 需要正确配置网络接入方式，路由表以及内核参数以允许 Xray bind 至地址块内的任意IP。

这里的**正确配置网络接入方式，路由表以及内核参数**具体指的是什么接入方式和内核配置？

例如，某服务器已经被路由到了`114:514:1919:810::/64`，并且设定其IP地址为`114:514:1919:810::1`，此时如果按默认的配置，直接在`sendThrough`中填上`"114:514:1919:810::/64"`，就可以了吗？

如果该服务器没有原生IPv6地址，而是使用[HE的IPv6隧道](https://tunnelbroker.net/)而获取到的IPv6地址，该如何配置呢？

---

以下是我的一台服务器，使用`netplan`，通过IPv6隧道接入。其中IP地址已被替换为虚构，假设服务器IPv4为`1.1.1.1`，被分配到的IPv6为`114:514:1919:810::2/64`，并被路由到的IPv6地址为`114:514:1919:811::/64`和`114:514:1919:812::/64`：

netplan配置文件
```
network:
  version: 2
  tunnels:
    he-ipv6:
      mode: sit
      remote: 1.1.2.1
      local: 1.1.1.1
      addresses:
        - "114:514:1919:810::2/64"
        - "114:514:1919:811::1/64"
        - "114:514:1919:812::1/64"
      routes:
        - to: default
          via: "114:514:1919:810::1"
        - to: "114:514:1919:811::/64"
          type: local
```

Xray部分配置：

```
{
  "tag": "direct",
  "protocol": "freedom",
  "settings": {
    "domainStrategy": "AsIs"
  },
  "sendThrough": "114:514:1919:812::/64"
}
```

现希望达到的目标是，客户端使用`114:514:1919:811::/64`中的任意地址均可访问到该服务器，该服务器访问网络使用`114:514:1919:812::/64`中的随机地址。但是，使用以上配置可以发现，可以通过`114:514:1919:811::/64`中的任意地址可以连上该服务器，但是客户端连上该服务器后，将会无法访问任何网站。移除`"sendThrough"`配置后恢复正常，访问网站全部使用`114:514:1919:812::1`。

恳请解答，谢谢。

`ifconfig`信息如下：
```
root@server:/# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 1.1.1.1  netmask 255.255.255.0  broadcast 1.1.1.0
        inet6 fe80::xxx:xxxx:xxxx:xxxx  prefixlen 64  scopeid 0x20<link>
        ether xx:xx:xx:xx:xx:xx  txqueuelen 1000  (Ethernet)

he-ipv6: flags=209<UP,POINTOPOINT,RUNNING,NOARP>  mtu 1480
        inet6 114:514:1919:810::2  prefixlen 64  scopeid 0x0<global>
        inet6 114:514:1919:811::1  prefixlen 64  scopeid 0x0<global>
        inet6 114:514:1919:812::1  prefixlen 64  scopeid 0x0<global>
        sit  txqueuelen 1000  (IPv6-in-IPv4)
```
