### DISCUSSION TITLE
wireguard 出站如何指定网卡？

### DISCUSSION THREAD

**Discussion by vrichv** [XTLS/Xray-core#4152] [General]
一台双栈vps，添加了HE的ipv6隧道地址
```
network:
  version: 2
  tunnels:
    he-ipv6:
      mode: sit
      remote: 1.1.1.1
      local: 10.0.0.1
      addresses:
        - "2001:f470:10::2/64"
        - "2001:f470:11::2/64"
      routes:
        - to: ::/0
          via: "2001:f470:10::1"
```
如果使用sing-box，可以直接配置bind-interface，指定he-ipv6网卡即可；
在xray中，如果使用sendThrough指定tunnel的ipv6地址，则无法连通网络，后来使用streamSettings -> sockopt则可以。
但是wireguard出站不支持streamSettings ,请问xray中如何指定网卡

```shell
"outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct",
      "streamSettings": {
        "sockopt": {
          "interface": "he-ipv6"
        }
      }
    }
```
