### DISCUSSION TITLE
How to run in k8s using ingress?

### DISCUSSION THREAD

**Discussion by sealab2066** [XTLS/Xray-core#4338] [Q&A]
Can someone help with kubernetes setup or can give fresh helm chart? I need simple setup with ingress along with another https domains

**Comment by shakibamoshiri** [comment]
what do you need ?

- make or get the container 
- write the yaml file 
- run it 

kuber sample file 

```yaml
apiVersion: apps/v1
kind: StatefulSet
# kind: Deployment
metadata:
  name: xrs-8006
  labels:
    app: xrs-8006
spec:
  serviceName: "xrs-8006"
  replicas: 1
  selector:
    matchLabels:
      app: xrs-8006
  template:
    metadata:
      labels:
        app: xrs-8006
    spec:
      hostNetwork: true
      nodeName: 100p3
      volumes:
        - name: local-persistent-storage
          hostPath:
            path: "/opt/storage/local/xrs/8006"
      containers:
        - name: xrs-8006
          # image: docker.io/library/3x-ui-3xui:latest
          image: docker.io/shmt/xrs:26.6.8
          imagePullPolicy: Never

          volumeMounts:
            - name: local-persistent-storage
              mountPath: "/etc/x-ui"
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
            runAsGroup: 0
          #securityContext:
          #  capabilities:
          #    add: ["NET_ADMIN", "SYS_TIME"]
      terminationGracePeriodSeconds: 10
      tolerations:
      - key: node.kubernetes.io/unreachable
        operator: Exists
        effect: NoExecute
        tolerationSeconds: 300
      - key: node.kubernetes.io/not-ready
        effect: NoExecute
        operator: Exists
        tolerationSeconds: 300

```
update yours accordingly
