### DISCUSSION TITLE
sni base rules or fallback based on sni without dest redirect

### DISCUSSION THREAD

**Discussion by wenerme** [XTLS/Xray-core#4361] [Performance]
我理解 fallback 类似基于 sni/port 的反向代理，反向代理的目标是一个 TCP 目标，例如

```yaml
- listen: 0.0.0.0
  port: 11040
  protocol: trojan
  tag: direct-trojan-in
  settings:
    clients:
    - password: *uuid
- listen: 0.0.0.0
  port: 11041
  protocol: vless
  tag: direct-vless-in
  settings:
    clients:
    - id: *uuid
      flow: xtls-rprx-vision
    decryption: none

- listen: 0.0.0.0
  port: 443
  protocol: vless
  tag: reality-vless-in
  settings:
    clients:
    - id: *uuid
      flow: xtls-rprx-vision
    decryption: none
    fallbacks:
    - name: direct-trojan.example.com
      dest: 11040
    - name: direct-vless.example.com
      dest: 11041
    # 
    - name: a-trojan.example.com
      dest: 11042
    # 更多
  streamSettings:
    security: reality
    realitySettings: *realitySettings
```

在这例子里，443 端口纯粹是为了用于做初始的入口，避免对外暴露过多端口，但这样实际路由下来例如 `11040` 是会直接走内部逻辑呢还是发起 TCP ？

如果是发起 TCP 那太多的这样 fallback 会有影响么？

> 这里能直接走内部 SNI 路由 mux 而不是发起 TCP 么？

我的目标实际是基于来源标识做路由

```yaml
- inboundTag:
  - direct-trojan-in
  - direct-vless-in
  outboundTag: direct-out
- inboundTag:
  - a-trojan-in
  - a-vless-in
  outboundTag: a-out
# 更多
```

但实际为了达到这样的目录是不是没必要弄这么多 inboundTag，希望有匹配来源 sni 的标识，或者匹配 uuid 的标识

```yaml
# 假设可以使用 uuid
- uuid: 1-1-1-1
  outboundTag: direct-out
# 假设可以判断来源 sni
- sourcrDomains:
  - direct-trojan.example.com
  - direct-vless.example.com
  outboundTag: direct-out
# 假设 inbound 有标签属性
- inboundLabel:
  - target: direct
  outboundTag: direct-out
```

其中不增加 inbound 的前提下，最好是能通过请求来的 sni 信息来判断。

> 我看到有 `user`, 这是唯一能在 rule 里面使用的用户信息，相当于支持 uuid 匹配，使用这个 user 来做筛选是正确的做法么？

我理解的 user 是应该尽量维持不变，避免客户端来回切换 uuid，但是切换 sni/servername 是相对容易的，所以我希望能通过 sni 来做路由。
