### DISCUSSION TITLE
Is the `v2ray.core.app.proxyman.command.HandlerService` deprecated on image: `teddysun/xray`?

### DISCUSSION THREAD

**Discussion by Kolyall** [XTLS/Xray-core#4456] [Q&A]
My docker container:
```
  xray:
    image: teddysun/xray
    container_name: xray
    restart: always
    volumes:
      - xray__config:/etc/xray
    ports:
      - "443:443" 
    networks:
      - my_network
```
My config:
```
  "api": {
    "listen": "0.0.0.0:8080",
    "services": [
      "ReflectionService",
      "HandlerService",
      "LoggerService",
      "RoutingService",
      "StatsService"
    ],
    "tag": "api"
  },
```

Command   `grpcurl -plaintext :8080 list` execution result on xray container:
```
~ # grpcurl -plaintext :8080 list
grpc.reflection.v1.ServerReflection
grpc.reflection.v1alpha.ServerReflection
v2ray.core.app.log.command.LoggerService
v2ray.core.app.proxyman.command.HandlerService
v2ray.core.app.router.command.RoutingService
v2ray.core.app.stats.command.StatsService
xray.app.log.command.LoggerService
xray.app.proxyman.command.HandlerService
xray.app.router.command.RoutingService
xray.app.stats.command.StatsService
```

But if I execute the command `list v2ray.core.app.proxyman.command.HandlerService` result is:
```
grpcurl -plaintext :8080 list v2ray.core.app.proxyman.command.HandlerService
Failed to list methods for service "v2ray.core.app.proxyman.command.HandlerService": Symbol not found: v2ray.core.app.proxyman.command.HandlerService
```

Is the `v2ray.core.app.proxyman.command.HandlerService` deprecated on docker image: `teddysun/xray`?
