### DISCUSSION TITLE
how can set rule for every new inbound that have specific pattern of tag

### DISCUSSION THREAD

**Discussion by mohamadrezamomeni** [XTLS/Xray-core#4607] [Q&A]
hello can we put regular expression in rules.rule.inputTag?

**Comment by i-eat-helicopter** [comment]
Assuming you're talking about routing rules, you can't do that without patching.

[regexp_inboundtag.patch.txt](https://github.com/user-attachments/files/19719804/regexp_inboundtag.patch.txt)

Patch with `git apply regexp_inboundtag.patch.txt`, then run `go build -o xray -trimpath -ldflags "-s -w" -v ./main`.

After that, you can use the `regexp:` prefix in the inboundTag like this

```yaml
log:
  # loglevel: info
  access: /dev/stdout
inbounds:
  - &in
    tag: a_1
    protocol: dokodemo-door
    port: 8001
    settings:
      address: 1.1.1.1
      port: 80
  - <<: *in
    tag: a_2
    port: 8002
  - <<: *in
    tag: a_x
    port: 8003
  - <<: *in
    tag: a_y
    port: 8004
  - <<: *in
    tag: b_1
    port: 8005
  - <<: *in
    tag: b_2
    port: 8006
  - <<: *in
    tag: other
    port: 8007

outbounds:
  - &out
    tag: out_a
    protocol: freedom
  - <<: *out
    tag: out_b
  - <<: *out
    tag: out_c

routing:
  rules:
    - inboundTag:
        - regexp:a_[0-9]+$
      outboundTag: out_a

    - inboundTag:
        - regexp:a_[a-z]+$
        - other
      outboundTag: out_b

    - inboundTag:
        - regexp:b_.*
      outboundTag: out_c
```
