### ISSUE TITLE
多重回落配置时，trojan兜底回落不生效

### ISSUE THREAD

**Issue by FansChou** [XTLS/Xray-core#1215]
使用的xray版本为1.5.5，我的服务端配置如下：
```yaml
log:
  error: "/var/log/xray/error.log"
  loglevel: info
  access: none
  dnsLog: false

dns:
  servers:
  - localhost

routing:
  domainStrategy: IPIfNonMatch
  rules:
  - type: field
    protocol:
    - bittorrent
    outboundTag: IPv4-out
  - type: field
    domain:
    - geosite:category-ads-all
    outboundTag: blackhole
  - type: field
    domain:
    - geosite:google-cn
    - domain:googleapis.cn
    outboundTag: IPv4-out
  - type: field
    domain:
    - geosite:cn
    - geosite:category-games@cn
    outboundTag: blackhole
  - type: field
    ip:
    - geoip:cn
    outboundTag: blackhole

outbounds:
- protocol: freedom
  settings:
    domainStrategy: UseIPv4
  tag: IPv4-out
- protocol: freedom
  settings:
    domainStrategy: UseIPv6
  tag: IPv6-out
- protocol: blackhole
  tag: blackhole

inbounds:
- tag: VLESSTCP
  protocol: vless
  port: 8443
  settings:
    clients:
    - id: uuid
      add: domain.com
      flow: xtls-rprx-direct
      email: domain.com_VLESS_XTLS/TLS-direct_TCP
    decryption: none
    fallbacks:
    - dest: "/dev/shm/trojan_TCP.sock"
      xver: 1
    - alpn: h2
      dest: "/dev/shm/h2c.sock"
      xver: 1
  streamSettings:
    network: tcp
    security: xtls
    xtlsSettings:
      minVersion: '1.3'
      alpn:
      - h2
      - http/1.1
      rejectUnknownSni: true
      certificates:
      - certificateFile: "/etc/xray/domain.com.crt"
        keyFile: "/etc/xray/domain.com.key"
        ocspStapling: 3600
        usage: encipherment
  sniffing:
    enabled: true
    destOverride:
    - http
    - tls
- tag: trojangRPCTCP
  protocol: trojan
  listen: "/dev/shm/trojan_gRPC.sock,0666"
  settings:
    clients:
    - password: uuid
      email: domain.com_trojan_gRPC
    fallbacks:
    - dest: "/dev/shm/default.sock"
  streamSettings:
    network: grpc
    grpcSettings:
      serviceName: domaincom
- tag: trojanTCP
  protocol: trojan
  listen: "/dev/shm/trojan_TCP.sock,0666"
  settings:
    clients:
    - password: uuid
      email: domain.com_trojan_tcp
    fallbacks:
    - dest: "/dev/shm/default.sock"
  streamSettings:
    network: tcp
    security: none
    tcpSettings:
      acceptProxyProtocol: true
```

接收`/dev/shm/default.sock`的是nginx，配置如下：
```
server {
        listen unix:/dev/shm/default.sock proxy_protocol;
        server_name domain.com;
        root /usr/share/nginx/html;

        set_real_ip_from 127.0.0.1;

        location /s/ {
                add_header Content-Type text/plain;
        }
        location / {
                add_header Strict-Transport-Security "max-age=15552000; preload" always;
        }
}
```

使用curl测试http/1.1访问域名`curl --http1.1 https://domain.com:8443`，得到结果
`curl: (52) Empty reply from server`

xray日志打印：
```
2022/09/09 14:10:14 [Info] [1472200107] proxy/vless/inbound: firstLen = 87
2022/09/09 14:10:14 [Info] [1472200107] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request version
2022/09/09 14:10:14 [Info] [1472200107] proxy/vless/inbound: realName = domain.com
2022/09/09 14:10:14 [Info] [1472200107] proxy/vless/inbound: realAlpn = http/1.1
2022/09/09 14:10:14 [Info] [2808813617] proxy/trojan: firstLen = 87
2022/09/09 14:10:14 [Info] [2808813617] proxy/trojan: fallback starts > proxy/trojan: not trojan protocol
2022/09/09 14:10:15 [Info] [2808813617] app/proxyman/inbound: connection ends > proxy/trojan: fallback ends > context canceled
```

配置参考的；https://xtls.github.io/Xray-docs-next/document/level-1/fallbacks-lv1.html
https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-XTLS-WHATEVER/config_server.json
