### ISSUE TITLE
[Trojan+gRPC+Caddy] unix socket not found in Caddy docker

### ISSUE THREAD

**Issue by 0xLem0nade** [XTLS/Xray-core#1281]
I have deployed Xray v1.6.1 on my server and client configured for Trojan with gRPC transport with docker compose, however the logs show a problem with Caddy trying to connect to the Xray socket `/dev/shm/Xray-Trojan-gRPC.socket`!

To add more context, I'm trying to offload TLS encryption to Caddy and reverse proxy the 443 port to Xray, everything works with the HTTP2 transport but not gRPC! My domain is managed by Cloudflare (DNS only for now, gray cloud) and the gRPC connection is enabled in my Cloudflare panel.

**Caddy logs:**
```
{"level":"debug","ts":1666737077.9969254,"logger":"http.handlers.reverse_proxy","msg":"upstream roundtrip","upstream":"unix//dev/shm/Xray-Trojan-gRPC.socket","duration":0.008244824,"request":{"remote_ip":"x.x.x.x","remote_port":"57150","proto":"HTTP/2.0","method":"POST","host":"mydomain.com","uri":"/myservice/Tun","headers":{"Te":["trailers"],"Content-Type":["application/grpc"],"User-Agent":["grpc-go/1.50.1"],"X-Forwarded-For":["x.x.x.x"],"X-Forwarded-Proto":["https"],"X-Forwarded-Host":["mydomain.com"]},"tls":{"resumed":false,"version":772,"cipher_suite":4867,"proto":"h2","server_name":"mydomain.com"}},"error":"dial unix /dev/shm/Xray-Trojan-gRPC.socket: connect: no such file or directory"}

{"level":"error","ts":1666737077.9971762,"logger":"http.log.error","msg":"dial unix /dev/shm/Xray-Trojan-gRPC.socket: connect: no such file or directory","request":{"remote_ip":"x.x.x.x","remote_port":"57150","proto":"HTTP/2.0","method":"POST","host":"mydomain.com","uri":"/myservice/Tun","headers":{"Content-Type":["application/grpc"],"User-Agent":["grpc-go/1.50.1"],"Te":["trailers"]},"tls":{"resumed":false,"version":772,"cipher_suite":4867,"proto":"h2","server_name":"mydomain.com"}},"duration":0.00883118,"status":502,"err_id":"aasgs9e03","err_trace":"reverseproxy.statusError (reverseproxy.go:1272)"}
```

**Xray client logs:**
```
2022/10/26 12:33:53 [Info] [3513186319] proxy/socks: TCP Connect request to tcp:push.services.mozilla.com:443
2022/10/26 12:33:53 [Info] [3513186319] app/dispatcher: default route for tcp:push.services.mozilla.com:443
2022/10/26 12:33:53 [Info] [3513186319] transport/internet/grpc: creating connection to tcp:mydomain.com:443
2022/10/26 12:33:53 [Info] [3513186319] proxy/trojan: tunneling request to tcp:push.services.mozilla.com:443 via mydomain.com:443
2022/10/26 12:33:53 tcp:127.0.0.1:49586 accepted tcp:push.services.mozilla.com:443
2022/10/26 12:33:53 [Info] [3513186319] app/proxyman/outbound: failed to process outbound traffic > proxy/trojan: connection ends > transport/internet/grpc/encoding: failed to fetch hunk from gRPC tunnel > rpc error: code = Unavailable desc = unexpected HTTP status code received from server: 502 (Bad Gateway); malformed header: missing HTTP content-type
2022/10/26 12:33:53 [Info] [3513186319] app/proxyman/inbound: connection ends > proxy/socks: connection ends > proxy/socks: failed to transport all TCP response > io: read/write on closed pipe
```

**xray-docker-compose.yml:**
```
version: "3.9"
services:
    xray:
        image: teddysun/xray:latest
        container_name: xray
        cap_add:
            - NET_ADMIN
            - CAP_NET_BIND_SERVICE
        restart: unless-stopped
        networks:
            - caddy
        volumes:
            - $PWD/etc/Trojan-Caddy.json:/etc/xray/config.json:ro
            - $PWD/log/:/var/log/xray/:rw
        command: [ "xray", "run", "-config", "/etc/xray/config.json" ]
        environment:
            - TZ=UTC

networks:
    caddy:
        external: true
```
**caddy-docker-compose.yml:**
```
version: "3.9"
services:
  caddy:
    image: 0xlem0nade/caddy:latest
    restart: unless-stopped
    container_name: caddy
    cap_add:
      - NET_ADMIN
      - CAP_NET_BIND_SERVICE
    networks:
      - caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/www:/srv
      - $PWD/log/:/var/log/
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true

networks:
  caddy:
    external: true
```
**Caddyfile:**
```
{
	order reverse_proxy before route
	log {
		level DEBUG
		output file /var/log/caddy.log {
			roll_size 10MiB
			roll_keep_for 3d
		}
	}
}

:443, mydomain.com {
	tls {
		protocols tls1.3
		ciphers TLS_CHACHA20_POLY1305_SHA256 TLS_AES_256_GCM_SHA384 TLS_AES_128_GCM_SHA256
		alpn h2
	}

	# Trojan gRPC
	@grpc {
		protocol grpc
		path /myservice/*
	}
	reverse_proxy @grpc unix//dev/shm/Xray-Trojan-gRPC.socket {
		transport http {
			versions h2c 2
		}
	}

	@host {
		host mydomain.com
	}
	route @host {
		header {
			Strict-Transport-Security "max-age=31536000; includeSubDomains; preload; always"
			X-Frame-Options "SAMEORIGIN"
			X-Content-Type-Options "nosniff"
			X-XSS-Protection "1; mode=block"
			Referrer-Policy "strict-origin"
		}
		file_server {
			root /srv
		}
	}
}

```
**server-config.json:**
```
//Redacted to inbound section
{
            "listen": "/dev/shm/Xray-Trojan-gRPC.socket,0666",
            "protocol": "trojan",
            "settings": {
                "clients": [
                    {
                        "password": "mypassword"
                    }
                ]
            },
            "streamSettings": {
                "network": "grpc",
                "grpcSettings": {
                    "serviceName": "myservice"
                },
                "security": "none"
            },
            "sniffing": {
                "enabled": true,
                "destOverride": [
                    "http",
                    "tls"
                ]
            }
        }
```

I have tried adding `/dev/shm/Xray-Trojan-gRPC.socket:/dev/shm/Xray-Trojan-gRPC.socket` inside both `docker-compose.yml` files, but it's not working!

**Comment by liaoliaots** [comment]
```yaml

services:
  xray:
    image: teddysun/xray:latest
    container_name: xray
    cap_add:
      - NET_ADMIN
      - CAP_NET_BIND_SERVICE
    restart: unless-stopped
    networks:
      - caddy
    volumes:
      - $PWD/etc/Trojan-Caddy.json:/etc/xray/config.json:ro
      - $PWD/log/:/var/log/xray/:rw
      - sockets:/dev/shm
    command: ['xray', 'run', '-config', '/etc/xray/config.json']
    environment:
      - TZ=UTC
  caddy:
    image: 0xlem0nade/caddy:latest
    restart: unless-stopped
    container_name: caddy
    cap_add:
      - NET_ADMIN
      - CAP_NET_BIND_SERVICE
    networks:
      - caddy
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/www:/srv
      - $PWD/log/:/var/log/
      - caddy_data:/data
      - caddy_config:/config
      - sockets:/dev/shm

networks:
  caddy:
    external: true

volumes:
  caddy_data:
    external: true
  caddy_config:
    external: true
  sockets:
```
