### ISSUE TITLE
Ubuntu 20.04 LTS Server Optimizations for Xray on heavy loads

### ISSUE THREAD

**Issue by zerodwide** [XTLS/Xray-core#1714]
Greetings!

I have a Bridge server with 5Gb/s port, 8core cpu, 32Gb memory, and about 4000 users connecting to it via VLESS+TCP+XTLS on XrayR v0.8.8.
and bridge is connected to 4 Main server each with 1Gb/s port, 8core cpu, 32Gb memory. (via 4 array item in vnext in outbound also with VLESS+TCP+XTLS)

My customers was experiencing a lot connection loss and getting disconnected from 5-30 seconds randomly.

I have checked main bottlenecks, like CPU, MEMORY, BANDWIDTH, but all of them was normal and below 20-30%.

then i figured out about these changes to bridge and main servers:

1. /etc/sysctl.conf
```
fs.file-max=9000000
fs.nr_open=9000000
fs.inotify.max_user_watches=3400000
net.core.somaxconn=9000000
net.ipv4.tcp_max_syn_backlog=9000000
net.core.netdev_max_backlog=9000000
net.ipv4.tcp_syncookies=0
```
2. /etc/systemd/user.conf & /etc/systemd/system.conf
```
DefaultLimitNOFILE=9000000
```
3. /etc/security/limits.conf
 ```
* soft nproc 9000000
* hard nproc 9000000
* soft nofile 9000000
* hard nofile 9000000
root soft nproc 9000000
root hard nproc 9000000
root soft nofile 9000000
root hard nofile 9000000
 ```

**then connections get much better with less delay and randomly completely disconnected.**

but connection still it is not perfect and lazy somehow. (in low loads, everything is great!)

here are some infos on my bridge server: (in main servers there are same numbers)

netstat -ant | grep ESTABLISHED | wc -l
```
6002
```

netstat -ant | wc -l
```
9890
```

XrayR connection config:
```
ConnectionConfig:
  Handshake: 4 # Handshake time limit, Second
  ConnIdle: 30 # Connection idle time limit, Second
  UplinkOnly: 2 # Time limit when the connection downstream is closed, Second
  DownlinkOnly: 4 # Time limit when the connection is closed after the uplink is closed, Second
  BufferSize: 64 # The internal cache size of each connection, kB
```

My Questions:

1. what are best advice to set in xray config? timeout, buffer. etc
2. should i use some connection based tunnel from bridge to server? like wireguard?
(note: i tried iptables, SSH port forwarding, GOST, GOST relay, all was worst than outbound in XrayR.)
3. is there another bottleneck in ubuntu which i should change?

thanks in advance
