### ISSUE TITLE
Reality突然无法访问，在两个小时前依然正常

### ISSUE THREAD

**Issue by lanvada** [XTLS/Xray-core#2366]
如题，我检查了服务器的IP和域名，都能正常访问
这是我的V2RayN程序中报的错误：
```
app/proxyman/outbound: failed to process outbound traffic > proxy/vless/outbound: failed to find an available destination > common/retry: [x509: certificate is valid for lovelive.xxx.net, not www.lovelive-anime.jp] > common/retry: all retry attempts failed
```
这是我的Xray配置：
``` JSON
{
  "log": {
    "access": "/var/log/xray/access.log",
    "error": "/var/log/xray/error.log",
    "loglevel": "warning"
  },
  "dns": {
    "servers": [
      "https+local://1.1.1.1/dns-query",
      "https+local://dns.google/dns-query",
      "localhost"
    ]
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "domain": [
          "geosite:openai",
          "geosite:cloudflare",
          "geosite:netflix",
          "geosite:spotify"
        ],
        "outboundTag": "warp"
      },
      {
        "type": "field",
        "domain": [
          "geosite:cn"
        ],
        "outboundTag": "warp-cn"
      },
      {
        "type": "field",
        "ip": [
          "geoip:cn"
        ],
        "outboundTag": "warp-cn"
      },
      {
        "type": "field",
        "ip": [
          "geoip:private"
        ],
        "outboundTag": "block"
      }
    ]
  },
  "inbounds": [
    {
      "listen": "0.0.0.0",
      "port": 443,
      "protocol": "vless",
      "settings": {
        "clients": [
          {
            ...
          },
          {
            ...
          }
        ],
        "decryption": "none"
      },
      "streamSettings": {
        "network": "tcp",
        "security": "reality",
        "realitySettings": {
          "show": false,
          "dest": "172.11.27.2:8082",
          "xver": 1,
          "serverNames": [
            "www.lovelive-anime.jp"
          ],
          "privateKey": "gFqWM8thEXdxtE0JPPS9oQfDCF9vFa7c6Vw-RK3Wbko",
          "maxTimeDiff": 4000,
          "shortIds": [
            "0010",
            "0011"
          ]
        }
      },
      "sniffing": {
        "enabled": false,
        "destOverride": [
          "http",
          "tls",
          "quic"
        ]
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "wireguard",
      "tag": "warp",
      "settings": {
        "secretKey": ...,
        "address": [
          "172.16.0.2/32",
          "2606:4700:110:89a0:f1a3:5075:b087:6fb2/128"
        ],
        "peers": [
          {
            "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
            "keepAlive": 4000,
            "allowedIPs": [
              "0.0.0.0/0",
              "::/0"
            ],
            "endpoint": "162.159.192.1:2408"
          }
        ],
        "reserved": [
          0,
          0,
          0
        ],
        "mtu": 1280
      }
    },
    {
      "protocol": "wireguard",
      "tag": "warp-cn",
      "settings": {
        "secretKey": ...,
        "address": [
          "172.16.0.2/32",
          "2606:4700:110:89a0:f1a3:5075:b087:6fb2/128"
        ],
        "peers": [
          {
            "publicKey": "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=",
            "keepAlive": 4000,
            "allowedIPs": [
              "0.0.0.0/0",
              "::/0"
            ],
            "endpoint": "162.159.192.1:2408"
          }
        ],
        "reserved": [
          0,
          0,
          0
        ],
        "mtu": 1280
      }
    },
    {
      "protocol": "blackhole",
      "tag": "block"
    }
  ],
  "policy": {
    "levels": {
      "0": {
        "handshake": 3,
        "connIdle": 180
      },
      "1": {
        "handshake": 2,
        "connIdle": 120
      }
    }
  }
}
```

**Comment by lanvada** [comment]
这是我的nginx配置：
```
user nginx;
worker_processes auto;

# error_log  /var/log/nginx/error.log;
error_log /var/log/nginx/error.log notice;
# error_log  /var/log/nginx/info.log  info;

pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    log_format main '[$time_local] $proxy_protocol_addr "$http_referer" "$http_user_agent"';
    access_log /var/log/nginx/access.log main;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ""      close;
    }

    map $proxy_protocol_addr $proxy_forwarded_elem {
        ~^[0-9.]+$        "for=$proxy_protocol_addr";
        ~^[0-9A-Fa-f:.]+$ "for=\"[$proxy_protocol_addr]\"";
        default           "for=unknown";
    }

    map $http_forwarded $proxy_add_forwarded {
        "~^(,[ \\t]*)*([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?(;([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?)*([ \\t]*,([ \\t]*([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?(;([!#$%&'*+.^_`|~0-9A-Za-z-]+=([!#$%&'*+.^_`|~0-9A-Za-z-]+|\"([\\t \\x21\\x23-\\x5B\\x5D-\\x7E\\x80-\\xFF]|\\\\[\\t \\x21-\\x7E\\x80-\\xFF])*\"))?)*)?)*$" "$http_forwarded, $proxy_forwarded_elem";
        default "$proxy_forwarded_elem";
    }

    server {
        listen 80;
        return 301 https://$host$request_uri;
    }

    server {
        # http2 on; 这条指令出现在1.25.1版本中 https://nginx.org/en/docs/http/ngx_http_v2_module.html
        listen                  172.11.27.2:8082 ssl proxy_protocol;
        http2                   on;

        set_real_ip_from        172.11.27.2;

        ssl_certificate         /cert/cloudecho/lovelive/cert.pem;
        ssl_certificate_key     /cert/cloudecho/lovelive/key.pem;

        ssl_protocols           TLSv1.2 TLSv1.3;
        ssl_ciphers             TLS13_AES_128_GCM_SHA256:TLS13_AES_256_GCM_SHA384:TLS13_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305;

        ssl_session_timeout     1d;
        ssl_session_cache       shared:SSL:10m;
        ssl_session_tickets     off;

        ssl_stapling            on;
        ssl_stapling_verify     on;
        ssl_trusted_certificate /cert/cloudecho/lovelive/cert.pem;
        resolver                1.1.1.1 valid=60s;
        resolver_timeout        2s;

# 使用 https://www.digitalocean.com/community/tools/nginx 生成的反向代理配置
        location / {
            sub_filter                         $proxy_host $host;
            sub_filter_once                    off;

            set $website                       www.lovelive-anime.jp;
            proxy_pass                         https://$website;
            resolver 1.1.1.1;

            proxy_set_header Host              $proxy_host;

            proxy_http_version                 1.1;
            proxy_cache_bypass                 $http_upgrade;

            proxy_ssl_server_name              on;

            proxy_set_header Upgrade           $http_upgrade;
            proxy_set_header Connection        $connection_upgrade;
            proxy_set_header X-Real-IP         $proxy_protocol_addr;
            proxy_set_header Forwarded         $proxy_add_forwarded;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host  $host;
            proxy_set_header X-Forwarded-Port  $server_port;

            proxy_connect_timeout              60s;
            proxy_send_timeout                 60s;
            proxy_read_timeout                 60s;
        }
    }
}
```

**Comment by lanvada** [comment]
我检查了服务器上的错误日志，也没有发现任何错误

**Comment by lanvada** [comment]
这是我的docker-compose.yml
```
version: '3'

services:

# Network Basic Services

  nginx:
    image: nginx
    volumes:
      - /home/ubuntu/docker-apps/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/ubuntu/docker-apps/var/log/nginx:/var/log/nginx
      - /home/ubuntu/docker-apps/cert:/cert:ro
    networks:
      net0:
        ipv4_address: 172.11.27.2
    ports:
      - "80:80/tcp"
    expose:
      - 8082
    restart: on-failure

  xray:
    image: teddysun/xray:latest
    volumes:
      - /home/ubuntu/docker-apps/etc/xray:/etc/xray
      - /home/ubuntu/docker-apps/var/log/xray:/var/log/xray
    networks:
      net0:
        ipv4_address: 172.11.27.3
    ports:
      - "443:443/tcp"
    depends_on:
      - nginx
    restart: on-failure
    
  # wgcf:
  #   image: neilpang/wgcf-docker:latest
  #   volumes:
  #     - /home/ubuntu/docker-apps/etc/wgcf:/wgcf
  #     - /home/ubuntu/docker-apps/lib/modules:/lib/modules
  #   networks:
  #     net0:
  #       ipv4_address: 172.11.27.4
  #   sysctls:
  #     net.ipv6.conf.all.disable_ipv6: 0
  #   cap_add:
  #     - NET_ADMIN
  #   privileged: true

networks:
  net0:
    driver: bridge
    ipam:
      config:
        - subnet: 172.11.0.0/16
          ip_range: 172.11.27.0/24
          gateway: 172.11.27.1

```
