### ISSUE TITLE
Docker安装xray后的日志问题

### ISSUE THREAD

**Issue by toyo2333** [XTLS/Xray-core#2415]
我是用docker安装的xray，配置文件里的日志相关的设置是这样的：
    "log": {
        "loglevel": "warning"
    },

我用docker logs xray -f 命令查看日志的时候发现，日常非常的长，要滚动很多屏幕。

我docker restart xray 之后再查看日志还是这样

我没有设置日志存储到文件，那么这些控制台的日志是存在哪里的？为什么重启了容器后还在呢？
请问这些日志在内存里是越来越多么？如何清理？我不想看到这么多屏的日志。。。

**Comment by FranzKafkaYu** [comment]
@toyo2333 https://github.com/XTLS/Xray-core/issues/1878

**Comment by wuruiwm** [comment]
@toyo2333 设置docker日志大小 会自动清理掉的

**Comment by toyo2333** [comment]
> @toyo2333 设置docker日志大小 会自动清理掉的

我在xray文档里没有看到日志大小的配置选项。我都没有保存到文件。

**Comment by wuruiwm** [comment]
@toyo2333 对于程序而言，属于程序的标准输出，并不是日志
对于docker容器而言，就是容器的日志而已
所以用docker  run的话就是
```
docker run --log-opt max-size=10mb my-container
```
docker-compose就是
```
services:
  my-service:
    image: my-image
    logging:
      driver: json-file
      options:
        max-size: 10m
```
