### ISSUE TITLE
transport/internet/tcp: REALITY: processed invalid connection

### ISSUE THREAD

**Issue by Qlub53** [XTLS/Xray-core#2724]
Cannot connect to Xray server via VLESS+Reality.
Not sure what I did wrong. I tried my best following the official examples for both server and client configs.

# Xray server log
```log
...
REALITY remoteAddr: <my>.<client>.<public>.<ip>:<port>
REALITY remoteAddr: <my>.<client>.<public>.<ip>:<port>	hs.c.AuthKey[:16]: [<hidden>]	AEAD: *aes.gcmAsm
REALITY remoteAddr: <my>.<client>.<public>.<ip>:<port>	hs.c.ClientVer: [1 8 2]
REALITY remoteAddr: <my>.<client>.<public>.<ip>:<port>	hs.c.ClientTime: 2023-11-14 **:**:**
REALITY remoteAddr: <my>.<client>.<public>.<ip>:<port>	hs.c.ClientShortId: [<hidden>]
REALITY remoteAddr: <my>.<client>.<public>.<ip>:<port>	hs.c.conn == conn: true
REALITY remoteAddr: <my>.<client>.<public>.<ip>:<port>	hs.c.handshakeStatus: 0
2023/11/14 **:**:** [Info] transport/internet/tcp: REALITY: processed invalid connection
...
```

# Server config
`Xray v1.8.4` server config, based off of https://github.com/chika0801/Xray-examples/blob/main/VLESS-XTLS-uTLS-REALITY/config_server.json
```yaml
{
  "log": {
    "loglevel": "info"
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "outboundTag": "block",
        "domain": [
          "geosite:category-ads-all",
          "geosite:cn"
        ]
      },
      {
        "type": "field",
        "outboundTag": "block",
        "ip": [
          "geoip:cn"
        ]
      }
    ]
  },
  "inbounds": [
    {
      "port": 443,
      "listen": "0.0.0.0",
      "protocol": "vless",
      "settings": {
          "clients": [
              {
                  "id": "MY_UUID",
                  "flow": "xtls-rprx-vision",
              }
          ],
          "decryption": "none"
      },
      "streamSettings": {
          "network": "tcp",
          "security": "reality",
          "realitySettings": {
              "show": true,
              "xver": 1,
              "dest": "www.lovelive-anime.jp:443",
              "serverNames": [
                  "www.apple.com"
              ],
              "privateKey": "<hidden>",
              "shortIds": [
                  "", "6ba85179e30d4fc2"
              ]
          }
      },
      "sniffing": {
          "enabled": true,
          "destOverride": [
              "http",
              "tls",
              "quic"
          ],
          "routeOnly": true
      }
    }
  ],
  "outbounds": [
    {
      "protocol": "freedom"
    },
    {
      "tag": "block",
      "protocol": "blackhole"
    }
  ]
}
```

# Client config
`Clash.Meta kernal v1.15.0` client config, based off of [Clash.Meta official example](https://github.com/MetaCubeX/Meta-Docs/blob/3a711a4ff02f5f2c90eedff2c73a0502e7769e7f/docs/config/proxies/vless.md#vless-reality-vision)
```yaml
...

proxies:
  - name: VLESS+Reality
    type: vless
    server: my.server.domain
    port: 443
    uuid: MY_UUID
    network: tcp
    tls: true
    udp: true
    flow: xtls-rprx-vision
    servername: www.apple.com
    reality-opts:
      public-key: <hidden>
      short-id: 6ba85179e30d4fc2
    client-fingerprint: chrome

...
```
