### ISSUE TITLE
代理 UDP 时如果被代理地址为域名似乎会出现不通的情况

### ISSUE THREAD

**Issue by KobeArthurScofield** [XTLS/Xray-core#2962]
### 问题描述
在使用 FakeIP 进行透明代理或者代理送出数据到服务端时附带的地址为域名的话，被代理的应用可能会出现连接问题。在单使用 Xray-core 时不影响直连。
这个问题在以下情况复现：

1. 在电脑上使用 FakeIP 配合 TUN 使用时，直连的数据很可能没有影响，被代理的数据反而会受影响（仅限需要先解析域名到 IP 的 UDP），比如访问 https://ip.skk.moe/stun 时，被代理的测试地址测试可能无法获得结果。如果 TeamSpeak 也被 TUN 接管，语音服务器地址域名落在被代理范围内时也会无法连接。不影响域名解析后路由为直连以及纯 IP 的对端连接。
2. 在手机上使用 v2rayNG 使用 FakeIP 时启用系统 VPN 服务时，使用例如 TeamSpeak 之类的应用，如果连接到的服务器（使用域名）落在路由规则的代理范围内，会出现无法连接的问题。不影响直连的服务器以及纯 IP。

服务端使用 Xray-core （所有版本均在发布后三天内更新，目前为 1.8.7），搭配客户端为 Xray-core 亦或是 sing-box 时均存在。但是如果数据送入入口前已经被解析为非 FakeIP 则不受该问题影响。
服务端使用 Xray-core （所有版本均在发布后三天内更新，目前为 1.8.7）

疑似与代理 UDP 时 IP 和域名的对应处理有关。

<details>
<summary>服务端日志</summary>

```
2024/01/22 08:39:14 [Info] [4137504723] proxy/vless/inbound: firstLen = 98
2024/01/22 08:39:14 [Info] [4137504723] proxy/vless/inbound: received request for tcp:v1.mux.cool:0
2024/01/22 08:39:14 [Info] [4137504723] common/mux: received request for udp:<被代理域名>:9987
2024/01/22 08:39:14 [Debug] app/dns: domain <被代理域名> will use DNS in order: [localhost]
2024/01/22 08:39:14 [Info] app/dns: Localhost got answer: <被代理域名> -> [<IP 地址 1> <IP 地址 2>]
2024/01/22 08:39:14 [Info] [4137504723] app/dispatcher: default route for udp:<被代理域名>:9987
2024/01/22 08:39:14 [Debug] app/dns: domain <被代理域名> will use DNS in order: [localhost]
2024/01/22 08:39:14 [Info] app/dns: Localhost got answer: <被代理域名> -> [<IP 地址 1>]
2024/01/22 08:39:14 [Info] transport/internet: replace destination with udp:<IP 地址 1>:9987
2024/01/22 08:39:14 [Debug] transport/internet: dialing to udp:<IP 地址 1>:9987
2024/01/22 08:39:14 [Info] [4137504723] proxy/freedom: connection opened to udp:<被代理域名>:9987, local endpoint [::]:65111, remote endpoint <IP 地址 1>:9987
// 以下为客户端中断连接
2024/01/22 08:39:37 [Info] [4137504723] common/mux: session 0 ends. > io: read/write on closed pipe

2024/01/22 08:39:47 [Info] [4137504723] app/proxyman/inbound: connection ends > proxy/vless/inbound: connection ends > context canceled
```

</details>

错误日志提供的信息不太多。打开 access log 可能会有发现。

<details>
<summary>服务端配置（最小化）</summary>

``` yaml
dns:
  hosts:
  servers:
    -
      address: localhost
      domains:
        - geosite:private
      skipFallback: false
  queryStrategy: UseIP
  disableCache: false
  disableFallback: false
  disableFallbackIfMatch: true
  tag: InternalDNSServer

routing:
  domainStrategy: IPIfNonMatch
  rules:
    -
      type: field
      ip:
        - geoip:private
      outboundTag: blocked

inbounds:
  -
    listen: "::"
    port: port1,port2
    protocol: vless
    settings:
      clients:
        -
          id: <valid uuid>
          level: 12
          email: <user>
          flow: xtls-rprx-vision
        -
          id: <valid uuid>
          level: 12
          email: <user>
          flow: xtls-rprx-vision
      decryption: none
      fallbacks:
        -
          dest: <address to HTTP/2>
          type: tcp
          xver: 0
    sniffing:
      enabled: true
      metadataOnly: true
    allocate:
      strategy: always
    streamSettings:
      network: tcp
      security: reality
      realitySettings:
        show: false
        dest: <address to borrow myself>
        type: tcp
        xver: 0
        serverNames:
          - <SNI borrowed from myself>
        privateKey: <valid key>
        minClientVer: "1.8.1"
        maxTimeDiff: 3600000
        shortIds:
          - <valid short ID>
          - <valid short ID>
      sockopt:
        tcpKeepAliveInterval: 75
        tcpKeepAliveIdle: 300
        tcpNoDelay: true
        tcpMptcp: true
        tcpCongestion: bbr
        acceptProxyProtocol: false
    tag: vless-vision-backend

outbounds:
  -
    protocol: freedom
    settings:
      userLevel: 11
    streamSettings:
      sockopt:
        domainStrategy: ForceIPv6v4
        tcpKeepAliveInterval: 90
        tcpKeepAliveIdle: 180
        tcpCongestion: bbr
        tcpNoDelay: true
        tcpMptcp: true
    tag: direct
  -
    protocol: blackhole
    settings:
      response:
        type: none
    tag: blocked
```

</details>

<details>
<summary>客户端日志（v2rayNG）</summary>

``` jsonc
{
    "dns": {
        "queryStrategy": "UseIP",
        "tag": "dns-server",
        "hosts": {
            "<REMOTE DNS>": [
                "<IP>"
            ],
            "<DOMESTIC DNS>": [
                "<IP>"
            ],
            "domain:localhost": [
                "::1",
                "127.0.0.1"
            ],
            "domain:test": [
                "::1",
                "127.0.0.1"
            ]
        },
        "servers": [
            {
                "address": "<REMOTE DNS>",
                "domains": [
                    "geosite:googlefcm"
                ],
                "skipFallback": true
            },
            {
                "address": "fakedns",
                "domains": [
                    "<ALL USED DOMAIN SET>"
                ]
            },
            {
                "address": "<DOMESTIC IP>",
                "domains": [
                    "geosite:private",
                    "<DIRECT DOMAIN>"
                ]
            },
            {
                "address": "<REMOTE DNS>",
                "domains": [
                    "<PROXY DOMAIN>"
                ],
                "skipFallback": true
            }
        ],
        "disableFallbackIfMatch": true
    },
    "fakedns": [
        {
            "poolSize": 32768,
            "ipPool": "198.18.0.0/15"
        },
        {
            "poolSize": 32768,
            "ipPool": "2001:2::/48"
        }
    ],
    "inbounds": [
        {
            "port": 10808,
            "listen": "127.0.0.1",
            "protocol": "socks",
            "tag": "socks",
            "settings": {
                "userLevel": 2,
                "auth": "noauth",
                "udp": true
            },
            "sniffing": {
                "destOverride": [
                    "fakedns"
                ],
                "enabled": true,
                "metadataOnly": true
            },
            "streamSettings": {
                "sockopt": {
                    "tcpKeepAliveIdle": -1,
                    "tcpKeepAliveInterval": -1,
                    "tcpNoDelay": true
                }
            }
        },
        {
            "port": 10809,
            "listen": "127.0.0.1",
            "protocol": "http",
            "tag": "http",
            "settings": {
                "userLevel": 2
            },
            "streamSettings": {
                "sockopt": {
                    "tcpKeepAliveIdle": -1,
                    "tcpKeepAliveInterval": -1,
                    "tcpNoDelay": true
                }
            }
        },
        {
            "port": 10853,
            "listen": "127.0.0.1",
            "protocol": "dokodemo-door",
            "tag": "dns-in",
            "settings": {
                "port": 53,
                "userLevel": 3,
                "address": "8.8.8.8",
                "network": "tcp,udp"
            },
            "streamSettings": {
                "sockopt": {
                    "tcpKeepAliveIdle": -1,
                    "tcpKeepAliveInterval": -1,
                    "tcpNoDelay": true
                }
            }
        }
    ],
    "log": {
        "access": "none",
        "loglevel": "warning",
        "dnsLog": true
    },
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "direct",
            "settings": {
                "userLevel": 4
            },
            "streamSettings": {
                "sockopt": {
                    "tcpKeepAliveIdle": 300,
                    "tcpKeepAliveInterval": 75,
                    "domainStrategy": "ForceIPv6v4",
                    "tcpMptcp": true,
                    "tcpNoDelay": true
                }
            }
        },
        {
            "protocol": "vless",
            "tag": "proxy",
            "mux": {
                "concurrency": -1,
                "xudpConcurrency": 8,
                "xudpProxyUDP443": "allow",
                "enabled": true
            },
            "settings": {
                "vnext": [
                    {
                        "port": <server port>,
                        "address": "<SERVER DOMAIN>",
                        "users": [
                            {
                                "level": 4,
                                "encryption": "none",
                                "flow": "xtls-rprx-vision-udp443",
                                "id": "<valid uuid>"
                            }
                        ]
                    }
                ]
            },
            "streamSettings": {
                "network": "tcp",
                "security": "reality",
                "realitySettings": {
                    "fingerprint": "random",
                    "publicKey": "<valid key>",
                    "serverName": "<SERVER DOMAIN>",
                    "shortId": "<valid short id>",
                    "spiderX": "/spyderx_page",
                    "show": false
                },
                "sockopt": {
                    "tcpKeepAliveIdle": 300,
                    "tcpKeepAliveInterval": 75,
                    "domainStrategy": "ForceIPv6v4",
                    "tcpMptcp": true,
                    "tcpNoDelay": true
                }
            }
        },
        {
            "protocol": "blackhole",
            "tag": "block",
            "settings": {
                "response": {
                    "type": "none"
                }
            }
        },
        {
            "protocol": "dns",
            "tag": "dns-out",
            "settings": {
                "userLevel": 3,
                "address": "2001:4860:4860::8844",
                "nonIPQuery": "skip"
            },
            "streamSettings": {
                "sockopt": {
                    "tcpKeepAliveIdle": 300,
                    "tcpKeepAliveInterval": 75,
                    "domainStrategy": "ForceIPv6v4",
                    "tcpNoDelay": true
                }
            }
        },
        {
            "protocol": "freedom",
            "tag": "DNSQExit",
            "settings": {
                "userLevel": 3
            },
            "streamSettings": {
                "sockopt": {
                    "tcpKeepAliveIdle": 300,
                    "tcpKeepAliveInterval": 75,
                    "domainStrategy": "ForceIPv6v4",
                    "tcpNoDelay": true
                }
            }
        }
    ],
    "policy": {
        "levels": {
            "2": {
                "bufferSize": 0,
                "connIdle": 1800,
                "downlinkOnly": 5,
                "handshake": 20,
                "uplinkOnly": 5
            },
            "3": {
                "bufferSize": 0,
                "connIdle": 180,
                "downlinkOnly": 4,
                "handshake": 4,
                "uplinkOnly": 4
            },
            "4": {
                "bufferSize": 64,
                "connIdle": 1800,
                "downlinkOnly": 5,
                "handshake": 20,
                "uplinkOnly": 5
            }
        }
    },
    "routing": {
        "domainMatcher": "hybrid",
        "domainStrategy": "IPIfNonMatch",
        "rules": [
            {
                "outboundTag": "dns-out",
                "type": "field",
                "inboundTag": [
                    "dns-in"
                ]
            },
            {
                "outboundTag": "proxy",
                "type": "field",
                "inboundTag": [
                    "dns-server"
                ],
                "ip": [
                    "<REMOTE DNS SERVER IP>"
                ]
            },
            {
                "outboundTag": "DNSQExit",
                "type": "field",
                "inboundTag": [
                    "dns-server"
                ]
            },
            {
                "outboundTag": "direct",
                "type": "field",
                "domain": [
                    "geosite:private",
                    "<DIRECT DOMAIN>"
                ]
            },
            {
                "outboundTag": "direct",
                "type": "field",
                "ip": [
                    "geoip:private"
                ]
            },
            {
                "outboundTag": "proxy",
                "type": "field",
                "domain": [
                    "<PROXY DOMAIN>"
                ]
            },
            {
                "outboundTag": "proxy",
                "type": "field",
                "ip": [
                    "<PROXY IP>"
                ]
            }
        ]
    }
}
```

</details>

这个问题可能会在引入 TUN 后变得很明显，也许可以通过建立对应的域名——地址对来缓解，只是如果一个 IP 可以被多个域名解析到时会比较麻烦，不知道有无办法可解。
