### ISSUE TITLE
基于域名的路由策略没有生效

### ISSUE THREAD

**Issue by howcrazy** [XTLS/Xray-core#3243]
我构建了一个测试配置，希望当访问指定域名时放行，访问其它域名时拦截。
实际效果确是无论访问什么域名，都被拦截。

**Docker配置**
```yaml
version: '3'

services:
  xray:
    image: teddysun/xray:latest
    command: /usr/bin/xray -config /etc/xray/config.json
    environment:
      TZ: Asia/Shanghai
    ports:
    - 12345:12345/tcp
    volumes:
    - ./xray_config.json:/etc/xray/config.json
    restart: unless-stopped
```

**xray配置**
```json
{
  "log": {
    "loglevel": "debug"
  },
  "inbounds": [
    {
      "protocol": "socks",
      "listen": "0.0.0.0",
      "port": "12345"
    }
  ],
  "outbounds": [
    {
      "protocol": "blackhole",
      "tag": "block"
    },
    {
      "protocol": "freedom",
      "tag": "direct"
    }
  ],
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "type": "field",
        "domain": [
          "domain:baidu.com"
        ],
        "outboundTag": "direct"
      }
    ]
  }
}
```

**访问**
```shell
HTTPS_PROXY=socks5://127.0.0.1:12345 curl https://www.baidu.com/
```
