### ISSUE TITLE
用户id验证失败

### ISSUE THREAD

**Issue by ZYM66** [XTLS/Xray-core#3431]
### 完整性要求

- [X] 我保证阅读了文档，了解所有我编写的配置文件项的含义，而不是大量堆砌看似有用的选项或默认值。
- [X] 我搜索了issues，没有发现已提出的类似问题。

### 版本

1.8.13

### 描述

服务端验证失败：
2024/06/06 07:56:25 [Info] [2679230895] proxy/vless/inbound: firstLen = 56
2024/06/06 07:56:25 [Info] [2679230895] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request user id
2024/06/06 07:56:25 [Info] [2679230895] proxy/vless/inbound: realName = v.yimingzheng.top
2024/06/06 07:56:25 [Info] [2679230895] proxy/vless/inbound: realAlpn = 
2024/06/06 07:56:25 [Info] [2679230895] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > read tcp xxxx:443->xxxxx:45928: use of closed network connection
手机客户端配置如下：
![IMG_4512](https://github.com/XTLS/Xray-core/assets/61892155/57baeb87-6cc6-49b7-b4e3-2663da8d44fd)
使用以下配置文件始终出现身份验证问题
```yml
 {
  "inbounds": [
    {
      "listen": "0.0.0.0",
      "port": "443",
      "protocol": "vless",
      "settings": {
        "client": [
          {
            "id": "123456",
            "level": 0,
            "flow": "xtls-rprx-vision"
          }
        ],
        "decryption": "none",
        "fallbacks": [
          {
            "dest": 80
          }
        ]
      },
      "streamSettings": {
        "network": "tcp",
        "security": "tls",
        "tlsSettings": {
          "serverName": "v.yimingzheng.top",
          "allowInsecure": false,
          "certificates": [
            {
              "certificateFile": "/etc/letsencrypt/live/v.yimingzheng.top/fullchain.pem",
              "keyFile": "/etc/letsencrypt/live/v.yimingzheng.top/privkey.pem"
            }
          ]
        }
      },
      "tag": "inbound"
    }

  ],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct"
    }
  ]
}
```
UUID我换了很多组，全部显示 invalid request user id

### 客户端配置

<details><pre><code>

clash:
```yml
proxies:
  - name: "JAvless"
    type: vless
    server: v.yimingzheng.top
    port: 443
    uuid: "123456"
    network: tcp
    tls: true
    flow: xtls-rprx-vision

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "JAvless"

rules:
  - MATCH,Proxy

```

小火箭:
![IMG_4512](https://github.com/XTLS/Xray-core/assets/61892155/57baeb87-6cc6-49b7-b4e3-2663da8d44fd)

</code></pre></details>

### 服务端日志

<details><pre><code>
2024/06/06 07:56:25 [Info] [2679230895] proxy/vless/inbound: firstLen = 56
2024/06/06 07:56:25 [Info] [2679230895] proxy/vless/inbound: fallback starts > proxy/vless/encoding: invalid request user id
2024/06/06 07:56:25 [Info] [2679230895] proxy/vless/inbound: realName = v.yimingzheng.top
2024/06/06 07:56:25 [Info] [2679230895] proxy/vless/inbound: realAlpn = 
2024/06/06 07:56:25 [Info] [2679230895] app/proxyman/inbound: connection ends > proxy/vless/inbound: fallback ends > proxy/vless/inbound: failed to fallback request payload > read tcp xxxx:443->xxxxx:45928: use of closed network connection
</code></pre></details>
