### ISSUE TITLE
xhttp h3重连

### ISSUE THREAD

**Issue by clcc2019** [XTLS/Xray-core#4070]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [ ] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

<img width="724" alt="image" src="https://github.com/user-attachments/assets/e0f39901-614f-41c2-accc-8a29d7606358">
<img width="596" alt="image" src="https://github.com/user-attachments/assets/d3affed0-56eb-4a97-bdc7-3db0e86be088">

xray client > nginx h3 > xray xhttp

### Reproduction Method

重启nginx后需要重启xray客户端才能连上，这里断开后能重连吗？

### Client config

 ```yaml
  streamSettings:
    network: xhttp
    security: tls
    xhttpSettings:
      headers:
        host: 11
      path: /images
      maxConcurrentUploads: 10-30
      scMinPostsIntervalMs: 10-30
      scMaxConcurrentPosts: 20
    tlsSettings:
      serverName: 11
      alpn: ["h3"]
      fingerprint: chrome
      allowInsecure: false
    sockopt:
      tcpMptcp: true
      tcpNoDelay: true
```

### Server config

<details><pre><code>

</code></pre></details>

### Client log

<details><pre><code>

</code></pre></details>

### Server log

<details><pre><code>

</code></pre></details>
