### ISSUE TITLE
With multiple file configurations, inbounds with the same tag are completely overwritten instead of updated.

### ISSUE THREAD

**Issue by zq1997** [XTLS/Xray-core#4252]
### Integrity requirements

- [X] I confirm that I have read the documentation, understand the meaning of all the configuration items I wrote, and did not pile up seemingly useful options or default values.
- [X] I provided the complete config and logs, rather than just providing the truncated parts based on my own judgment.
- [X] I searched issues and did not find any similar issues.
- [X] The problem can be successfully reproduced in the latest Release

### Description

I am using multi-file configuration, and my expectation is this: maintain a `common.yaml`, in which the inbound does not have the `port` and `clients` fields, and then provide the corresponding settings in each `user-xxx.yaml`; in this way, I can start multiple services to serve different users on different ports.

But in fact, I found that xray will use the entire inbound object with the same tag in `user-xxx.yaml` to replace the one in `common.yaml`, instead of updating and supplementing it. As a result, there is nothing in the new inbound object except `port` and `clients`.

## common.yaml
```yaml
dns:
  servers:
    - 8.8.8.8
    - 1.1.1.1

inbounds:
- tag: tcp-in
  protocol: vless
  settings:
    decryption: none
    fallbacks:
    - dest: example.com:80
      xver: 0
  streamSettings:
    security: tls
    rejectUnknownSni: true
    tlsSettings:
      alpn: ['http/1.1', 'h2', 'h3']
      certificates:
      - certificateFile: /etc/letsencrypt/live/xxx/fullchain.pem
        keyFile: /etc/letsencrypt/live/xxx/privkey.pem
  sniffing:
    enabled: true
    destOverride:
    - http
    - tls

outbounds:
- protocol: freedom
  tag: default
```

## user-1.yaml
```yaml
inbounds:
- tag: tcp-in
  port: 2048
  settings:
    clients:
    - id: id-xxxxxxx
      flow: xtls-rprx-vision
```

## dump the merged config
```sh
xray run -c common.yaml -c user-1.yaml -dump
```

```
{
    "dns": {
        "disableCache": false,
        "disableFallback": false,
        "disableFallbackIfMatch": false,
        "servers": [
            {
                "Address": "8.8.8.8",
                "Port": 0,
                "SkipFallback": false
            },
            {
                "Address": "1.1.1.1",
                "Port": 0,
                "SkipFallback": false
            }
        ]
    },
    "inbounds": [
        {
            "port": 2048,
            "settings": {
                "clients": [
                    {
                        "flow": "xtls-rprx-vision",
                        "id": "id-xxxxxxx"
                    }
                ]
            },
            "tag": "tcp-in"
        }
    ],
    "outbounds": [
        {
            "protocol": "freedom",
            "tag": "default"
        }
    ],
    "port": 0
}
```

### Client config

-

### Server config

-

### Client log

-

### Server log

-
