### ISSUE TITLE
[feature request] support proxy relay chains like in clash

### ISSUE THREAD

**Issue by hronro** [XTLS/Xray-core#518]
reference (wiki from clash):

```yaml
proxy-groups:
  # relay chains the proxies. proxies shall not contain a relay. No UDP support.
  # Traffic: clash <-> http <-> vmess <-> ss1 <-> ss2 <-> Internet
  - name: "relay"
    type: relay
    proxies:
      - http
      - vmess
      - ss1
      - ss2
```
