### ISSUE TITLE
[Feature Request] 支持toml作为config格式

### ISSUE THREAD

**Issue by xiruizhao** [XTLS/Xray-core#75]
Urgency: low
json可轻松转换成支持评论和explicit typing的toml
例如https://github.com/XTLS/Xray-examples/blob/main/VLESS-TCP-XTLS-WHATEVER/config_client/vless_tcp_xtls.json 转换后是
```toml
[log]
loglevel = "warning"

[[inbounds]]
port = 10800
listen = "127.0.0.1"
protocol = "socks"

  [inbounds.settings]
  udp = true

[[outbounds]]
protocol = "vless"

[[outbounds.settings.vnext]]
# 换成你的域名或服务器 IP（发起请求时无需解析域名了）
address = "example.com"
port = 443

  [[outbounds.settings.vnext.users]]
  # 填写你的 UUID
  id = ""
  flow = "xtls-rprx-direct"
  encryption = "none"
  level = 0

  [outbounds.streamSettings]
  network = "tcp"
  # 需要使用 XTLS
  security = "xtls"

    [outbounds.streamSettings.xtlsSettings]
    # 换成你的域名
    serverName = "example.com"
```
