### ISSUE TITLE
fallback的dest能否修改校验规则，使其支持域名解析，方便在docker中使用

### ISSUE THREAD

**Issue by sujingclg** [XTLS/Xray-core#759]
如题，在docker中使用时，由于docker支持配置hostname，在容器内部是作为域名使用的，但是目前fallback的dest校验规则只能支持到ip，配置域名直接报错，导致使用docker部署xray和nginx时必须将xray容器的dest配置到宿主机的IP上，然后让nginx的容器也暴露端口在宿主机上才能使用，不是太方便。以下是相关代码。
```json
       "fallbacks": [
          {
            "dest": "192.168.7.201:8080" //  希望支持 proxy-xray:80 的配置方式
          }
```

```yml
version: "3.9"

services:

  proxy:
    hostname: proxy-xray
    image: nginx
    restart: always
    ports:
      - 8080:80
    container_name: proxy-xray
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html

  xray:
    image: teddysun/xray
    restart: always
    ports:
      - 443:443
    container_name: xray
    volumes:
      - ./config.json:/etc/xray/config.json
      - ./xray_log:/var/log/xray
      - ./xray_cert:/ect/xray/cert
```
